---

  - name: Include vars file
    include_vars: ../vars/vars.yml
    no_log: True

    
  - name: Include lauch scan role vars
    include_vars: ../vars/report_req_vars.yml
    no_log: True

  - block:
     - block:
        - name: Send an email {{date}} {{time}}
          include_role:
            name: common/send_email
          vars:
            mail_subject: Scan successful
            mail_body: Hi team, scaninng has been successfully done on requested scan site {{ scan_site_name }} with assets {{}}.'
            attachment_file:  "/{{ report_directory }}/{{scan_name}}_{{ansible_date_time.date}}_{{ansible_date_time.time}}.csv"
          # mail:
          #  host: smtp.gmail.com
          #  port: 587
          #  username: "{{smtp_username}}"
          #  password: "{{smtp_password}}"
          #  to: "{{email_id}}"
          #  subject: Scan successful 
          #  body: 'Hi team, scaninng has been successfully done on requested scan site {{ scan_site_name }} with assets {{}}.'
          #  attach: "/{{ report_directory }}/{{scan_name}}_{{ansible_date_time.date}}_{{ansible_date_time.time}}.csv"
          # delegate_to: localhost
        - debug:
           msg: "scan done"
       when: ' {{ flag }} == false '
    

     - name: Perform tasks to create a work order on bmc Remedy if vulnerabilities are found on assets {{date}} {{time}}
       block:
        
        - name: Create a zip format of report file
          archive:
           path: /{{ report_directory }}/{{scan_name}}_{{ansible_date_time.date}}_{{ansible_date_time.time}}.csv
           format: zip

        - name: Send an email with report
          include_role:
            name: common/send_email
          vars:
            mail_subject: Vulnerabilities found on assets by scan {{scan_name}}
            mail_body: 'Hi team, scaninng has been successfully done on requested scan site {{ scan_site_name }} with assets {{ output.stdout_lines }} identified for vulnerabilities.'
            attachment_file: "/{{ report_directory }}/{{scan_name}}_{{ansible_date_time.date}}_{{ansible_date_time.time}}.csv.zip"
          # mail:
          #  host: smtp.gmail.com
          #  port: 587
          #  username: "{{smtp_username}}"
          #  password: "{{smtp_password}}"
          #  to: "{{email_id}}"
          #  subject: Vulnerabilities found on assets by scan {{scan_name}}
          #  body: 'Hi team, scaninng has been successfully done on requested scan site {{ scan_site_name }} with assets {{ output.stdout_lines }} identified for vulnerabilities.'
          #  attach: "/{{ report_directory }}/{{scan_name}}_{{ansible_date_time.date}}_{{ansible_date_time.time}}.csv.zip"
          #delegate_to: localhost
       
        - name: Authenticate to bmc Remedy AR system and generate a token {{date}} {{time}}
          ignore_errors: true
          uri:
           url: https://{{remedy_host}}/jwt/login
           body_format: json
           body: {
        "username": "{{username}}",
        "password": "{{password}}"
       }
           method: POST
           status_code : 201
          register: authorised_token
 
        - name: Creating a bmc Remedy work order {{date}} {{time}}
          ignore_errors: true
          uri:
           url: http://{{remedy_host}}/api/arsys/v1/entry/WOI:WorkOrderInterface_Create/
           method: POST
           headers:
           - Authorization: "{{authorised_token}}"
           - Content-Type: "Application/Json"
           body: "{{work_order_request}}"
           status_code: 201
          register: work_order_created
       when: ' {{ flag }} == true '
    
    rescue:
      - name: Send an email if any task fails {{date}} {{time}}
        include_role:
         name: common/send_email
        vars:
         mail_subject: Failed to create a work order on bmc Remedy ITSM for {{scan_name}}
         mail_body: 'Hi team, failed to work orfder on bmc Remedy ITSM for {{scan_site_name}} and scan name {{scan_name}} .'
        # mail:
        #  host: smtp.gmail.com
        #  port: 587
        #  username: "{{smtp_username}}"
        #  password: "{{smtp_password}}"
        #  to: "{{ email_id }}"
        #  subject: Failed to create a work order on bmc Remedy ITSM for {{scan_name}}
        #  body: 'Hi team, failed to work orfder on bmc Remedy ITSM for {{scan_site_name}} and scan name {{scan_name}} .'
        #delegate_to: localhost
          
      - name: Abort this role tasks execution if no scan was triggered {{date}} {{time}}
        fail:
          msg: Aboring playbook execution, as scan launch failed
        when: '{{ authorised_token }} != 201 or {{ work_order_created }} != 201 '
    
 
